// config.js — generated by SLOT FORGE
const GameConfig = {
    gameId: "kingpin_s_fortune",
    mechanics: {
        cols: 5,
        rows: 3,
        enableCascading: false,
        lines: 20,
        featureBuyCostMulti: 100
    },
    paylines: [[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,2,2],[2,2,1,0,0],[1,0,1,2,1],[1,2,1,0,1],[1,0,0,1,2],[1,2,2,1,0],[0,1,0,1,0],[2,1,2,1,2],[0,1,1,1,0],[2,1,1,1,2],[0,0,2,0,0],[2,2,0,2,2],[1,1,0,1,1],[1,1,2,1,1],[0,2,0,2,0]],

    assets: {
        images: {
            bg: `background.jpg`,
            symbols: {
                1: `s1.png`,                 2: `s2.png`,                 3: `s3.png`,                 4: `s4.png`,                 5: `s5.png`,                 6: `s6.png`,                 7: `s7.png`,                 8: `s8.png`,                 9: `s9.png`,                 10: `WILD.png`,                 11: `SCATTER.png`,                 20: `gold.png`
            }
        },
        audio: {
            bgmMain: `bgm_main.mp3`,             bgmFree: `bgm_free.mp3`,             sfxSpin: `sfx_spin.mp3`,             sfxStop: `sfx_stop.mp3`
        }
    },
    symbols: {
        1: { type: 'high', payouts: {3:15,4:40,5:150}, weightBase: 2, inFree: true },
        2: { type: 'high', payouts: {3:10,4:30,5:100}, weightBase: 3, inFree: true },
        3: { type: 'high', payouts: {3:8,4:20,5:75}, weightBase: 5, inFree: true },
        4: { type: 'mid', payouts: {3:6,4:15,5:55}, weightBase: 10, inFree: true },
        5: { type: 'mid', payouts: {3:4,4:12,5:45}, weightBase: 12, inFree: true },
        6: { type: 'low', payouts: {3:3,4:8,5:30}, weightBase: 15, inFree: true },
        7: { type: 'low', payouts: {3:2,4:6,5:25}, weightBase: 18, inFree: true },
        8: { type: 'low', payouts: {3:1,4:4,5:18}, weightBase: 20, inFree: true },
        9: { type: 'low', payouts: {3:0.5,4:2,5:12}, weightBase: 25, inFree: true },
        10: { type: 'wild', weightBase: 1.5, inFree: true },
        11: { type: 'scatter', payouts: {3:2,4:10,5:100}, weightBase: 7.5, inFree: true },
        20: { type: 'coin', weightBase: 18, inFree: true }
    }
};

export default GameConfig;